run:
  timeout: 1m
  issues-exit-code: 1
  tests: false
  modules-download-mode: readonly
  go: '1.20'
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - revive
    - gosec
    - lll
    - misspell
    - nakedret
    - noctx
    - prealloc
    - rowserrcheck
    - exportloopref
    - stylecheck
    - unconvert
    - unparam
    - whitespace
linters-settings:
  funlen:
    lines: 90
    statements: 50
issues:
  exclude-rules:
    - path: /*_test.go
      linters:
        - funlen
        - fieldalignment
        - noctx
        - exportloopref