app:
  rest:
    enabled: true
    name: gotinder
    port: 8080
store:
  postgresql:
    name: gotinder_db
    user: postgres
    password: postgres
    host: store-pg
    port: "5432"
  migration:
    tablename: gotinder_migrations
  redis:
    database: 1
    password: redis
    host: store-redis
    port: 6379
