app:
  rest:
    enabled: true
    name: auth
    port: 8080
store:
  postgresql:
    name: gotinder_db
    user: postgres
    password: postgres
    host: localhost
    port: "5432"
  migration:
    tablename: gotinder_migrations
